version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=postgres_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3050:80"
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./exercise-tracker-client
    volumes:
      - /app/node_modules
      - ./exercise-tracker-client:/app
  api:
    depends_on:
      - postgres
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    environment:
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
    volumes:
      - /app/node_modules
      - ./server:/app
volumes:
  pgdata:
